class Wow::Spell < ActiveRecord::Base
  SCHOOLS = %w(physical holy fire nature frost shadow arcane)
  AURA_NAMES = [
      'None',
      'Bind Sight',
      'Mod Possess',
      'Periodic Damage',
      'Dummy',
      'Mod Confuse',
      'Mod Charm',
      'Mod Fear',
      'Periodic Heal',
      'Mod Attack Speed',
      'Mod Threat',
      'Taunt',
      'Stun',
      'Mod Damage Done',
      'Mod Damage Taken',
      'Damage Shield',
      'Mod Stealth',
      'Mod Detect',
      'Mod Invisibility',
      'Mod Invisibility Detection',
      'OBS Mod Intellect',
      'OBS Mod Spirit',
      'Mod Resistance',
      'Periodic Trigger',
      'Periodic Energize',
      'Pacify',
      'Root',
      'Silence',
      'Reflect Spells %',
      'Mod Stat',
      'Mod Skill',
      'Mod Speed',
      'Mod Speed Mounted',
      'Mod Speed Slow',
      'Mod Increase Health',
      'Mod Increase Energy',
      'Shapeshift',
      'Immune Effect',
      'Immune State',
      'Immune School',
      'Immune Damage',
      'Immune Dispel Type',
      'Proc Trigger Spell',
      'Proc Trigger Damage',
      'Track Creatures',
      'Track Resources',
      'Mod Parry Skill',
      'Mod Parry Percent',
      'Mod Dodge Skill',
      'Mod Dodge Percent',
      'Mod Block Skill',
      'Mod Block Percent',
      'Mod Crit Percent',
      'Periodic Leech',
      'Mod Hit Chance',
      'Mod Spell Hit Chance',
      'Transform',
      'Mod Spell Crit Chance',
      'Mod Speed Swim',
      'Mod Creature Dmg Done',
      'Pacify & Silence',
      'Mod Scale',
      'Periodic Health Funnel',
      'Periodic Mana Funnel',
      'Periodic Mana Leech',
      'Haste - Spells',
      'Feign Death',
      'Disarm',
      'Mod Stalked',
      'School Absorb',
      'Extra Attacks',
      'Mod School Spell Crit Chance',
      'Mod Power Cost',
      'Mod School Power Cost',
      'Reflect School Spells %',
      'Mod Language',
      'Far Sight',
      'Immune Mechanic',
      'Mounted',
      'Mod Dmg %',
      'Mod Stat %',
      'Split Damage',
      'Water Breathing',
      'Mod Base Resistance',
      'Mod Health Regen',
      'Mod Power Regen',
      'Create Death Item',
      'Mod Dmg % Taken',
      'Mod Health Regen Percent',
      'Periodic Damage Percent',
      'Mod Resist Chance',
      'Mod Detect Range',
      'Prevent Fleeing',
      'Mod Uninteractible',
      'Interrupt Regen',
      'Ghost',
      'Spell Magnet',
      'Mana Shield',
      'Mod Skill Talent',
      'Mod Attack Power',
      'Auras Visible',
      'Mod Resistance %',
      'Mod Creature Attack Power',
      'Mod Total Threat (Fade)',
      'Water Walk',
      'Feather Fall',
      'Hover',
      'Add Flat Modifier',
      'Add % Modifier',
      'Add Class Target Trigger',
      'Mod Power Regen %',
      'Add Class Caster Hit Trigger',
      'Override Class Scripts',
      'Mod Ranged Dmg Taken',
      'Mod Ranged % Dmg Taken',
      'Mod Healing',
      'Regen During Combat',
      'Mod Mechanic Resistance',
      'Mod Healing %',
      'Share Pet Tracking',
      'Untrackable',
      'Empathy (Lore, whatever)',
      'Mod Offhand Dmg %',
      'Mod Power Cost %',
      'Mod Ranged Attack Power',
      'Mod Melee Dmg Taken',
      'Mod Melee % Dmg Taken',
      'Rngd Atk Pwr Attckr Bonus',
      'Mod Possess Pet',
      'Mod Speed Always',
      'Mod Mounted Speed Always',
      'Mod Creature Ranged Attack Power',
      'Mod Increase Energy %',
      'Mod Max Health %',
      'Mod Interrupted Mana Regen',
      'Mod Healing Done',
      'Mod Healing Done %',
      'Mod Total Stat %',
      'Haste - Melee',
      'Force Reaction',
      'Haste - Ranged',
      'Haste - Ranged (Ammo Only)',
      'Mod Base Resistance %',
      'Mod Resistance Exclusive',
      'Safe Fall',
      'Charisma',
      'Persuaded',
      'Add Creature Immunity',
      'Retain Combo Points',
      'Resist Pushback',
      'Mod Shield Block %',
      'Track Stealthed',
      'Mod Detected Range',
      'Split Damage Flat',
      'Stealth Level Modifier',
      'Mod Water Breathing',
      'Mod Reputation Gain',
      'Mod Pet Damage'
  ]

  EFFECTS = [
      'None',
      'Instakill',
      'School Damage',
      'Dummy',
      'Portal Teleport',
      'Teleport Units',
      'Apply Aura',
      'Environmental Damage',
      'Power Drain',
      'Health Leech',
      'Heal',
      'Bind',
      'Portal',
      'Ritual Base',
      'Ritual Specialize',
      'Ritual Activate Portal',
      'Quest Complete',
      'Weapon Damage + (noschool)',
      'Resurrect',
      'Extra Attacks',
      'Dodge',
      'Evade',
      'Parry',
      'Block',
      'Create Item',
      'Weapon',
      'Defense',
      'Persistent Area Aura',
      'Summon',
      'Leap',
      'Energize',
      'Weapon % Dmg',
      'Trigger Missile',
      'Open Lock',
      'UNUSED',
      'Apply Area Aura',
      'Learn Spell',
      'Spell Defense',
      'Dispel',
      'Language',
      'Dual Wield',
      'Summon Wild',
      'Summon Guardian',
      'UNUSED',
      'Skill Step',
      'UNUSED',
      'Spawn',
      'Spell Cast UI',
      'Stealth',
      'Detect',
      'Summon Object',
      'Force Critical Hit',
      'Guarantee Hit',
      'Enchant Item Permanent',
      'Enchant Item Temporary',
      'Tame Creature',
      'Summon Pet',
      'Learn Pet Spell',
      'Weapon Damage +',
      'Open Lock (Item)',
      'Proficiency',
      'Send Event',
      'Power Burn',
      'Threat',
      'Trigger Spell',
      'Health Funnel',
      'Power Funnel',
      'Heal Max Health',
      'Interrupt Cast',
      'Distract',
      'Pull',
      'Pickpocket',
      'Add Farsight',
      'Summon Possessed',
      'Summon Totem',
      'Heal Mechanical',
      'Summon Object (Wild)',
      'Script Effect',
      'Attack',
      'Sanctuary',
      'Add Combo Points',
      'Create House',
      'Bind Sight',
      'Duel',
      'Stuck',
      'Summon Player',
      'Activate Object',
      'Summon Totem (slot 1)',
      'Summon Totem (slot 2)',
      'Summon Totem (slot 3)',
      'Summon Totem (slot 4)',
      'Threat (All)',
      'Enchant Held Item',
      'Summon Phantasm',
      'Self Resurrect',
      'Skinning',
      'Charge',
      'Summon Critter',
      'Knock Back',
      'Disenchant',
      'Inebriate',
      'Feed Pet',
      'Dismiss Pet',
      'Reputation',
      'Summon Object (slot 1)',
      'Summon Object (slot 2)',
      'Summon Object (slot 3)',
      'Summon Object (slot 4)',
      'Dispel Mechanic',
      'Summon Dead Pet',
      'Destroy All Totems',
      'Durability Damage',
      'Summon Demon',
      'Resurrect (Flat)',
      'Attack Me',
      '',
      '',
      '',
      'Require Skill'
  ]
  paginates_per 25

  self.table_name_prefix = 'wow_'

  belongs_to :icon, foreign_key: :spell_icon_id
  belongs_to :range
  belongs_to :cast_time, foreign_key: :spell_cast_time_id
  belongs_to :dispel_type
  belongs_to :duration
  belongs_to :mechanic

  default_scope { order('name_en ASC') }

  def name
    name_en
  end

  def rank
    rank_en
  end

  def school
    SCHOOLS[self[:resistance_id]]
  end

  def cooldown
    if (self[:cooldown] % 1000) > 0
      self[:cooldown]/1000.0
    else
      self[:cooldown]/1000
    end
  end

  def effect_name(i)
    EFFECTS[i]
  end

  def aura_name(i)
    AURA_NAMES[i]
  end

  %w(id misc_value radius aura base_points item_type amplitude trigger_spell).each do |meth|
    define_method("effect_#{meth}") { |i| self["effect_#{i}_#{meth}".to_sym] }
  end
end
